# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Weekly pre-commit autoupdate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 0"

permissions:
  contents: read

jobs:
  auto-update-pre-commit:
    permissions:
      contents: write
      pull-requests: write
    uses: bemanproject/infra-workflows/.github/workflows/reusable-beman-update-pre-commit.yml@13d8237273e7f4cd4a739f1ceb6539f5aec3f50d # 1.1.0
    secrets:
      APP_ID: ${{ secrets.AUTO_PR_BOT_APP_ID }}
      PRIVATE_KEY: ${{ secrets.AUTO_PR_BOT_PRIVATE_KEY }}
